.github/workflows/main.yaml
This PR enables the unit tests in composableai. Some packages are excluded on purpose because their tests are failing, we can fix them later on. This PR is related to
* https://github.com/becomposable/studio/issues/159
=> Enable unit tests

packages/client/src/store/TypesApi.ts, pnpm-lock.yaml
Issue:
- https://github.com/becomposable/studio/issues/413
Information:
- method `getTypeByName` was calling the endpoint `/api/v1/types` that is returning `a list of types` based on search criteria
- `Zeno worker` is expecting `an object` and `not a list`, leading to non mapped type on document created from InteractionResult
- create an endpoint `/api/v1/types/name/:name` on `zeno server` to retrieve needed object
=> bug(413) Update getTypeByName logic

packages/cli/package.json, packages/cli/src/objects/commands.ts, pnpm-lock.yaml
Issue:
- https://github.com/becomposable/studio/issues/421
Information:
- Files were uploaded with mime_type `application/octet-stream`
- `application/octet-stream` objects where not triggering `sys:SelectDocumentType` because they `don't have any text`
- Resolving mime_type before uploading the file fix the issue (mimic uploading a file using dropzone in content object view because the type is also resolved there)
=> bug(421) Set mime-type when uploading an object

packages/cli/src/utils/console.ts
Only clear the stream if the command line is connected to a terminal (isTTY=true), otherwise, don't try to clear it because the function will raise an error as this action is not available:
```
file:///home/runner/work/studio/studio/out/composableai/packages/cli/lib/utils/console.js:152
this.stream.clearLine(0);
^
TypeError: this.stream.clearLine is not a function
```
=> Only clear stream if it is possible

packages/workflow/src/iterative-generation/iterativeGenerationWorkflow.ts
Currently LLMs are failing on the generation of the table of content (ToC) because the generation is complex. Let's increase the timeout on the Temporal side to give it more time for the execution.
=> Increase startToCloseTimeout for interactive generation

.github/workflows/main.yaml
Since https://github.com/becomposable/composableai/commit/78019c84ab1c9e28eaf76e97f395a7e9d2d3d7f0 memory-related source code have been moved to another repository called [becomposable/memory](https://github.com/becomposable/memory). So setting up unit tests for this package is not relevant anymore.
=> Fix: remove memory-test

packages/common/src/payload.ts
Adds optional exportAll property to export API payload
https://github.com/becomposable/studio/issues/529
Used for export all objects functionality.
=> Add exportAll property to export payload

packages/cli/src/index.ts, packages/cli/src/run/executor.ts, packages/common/src/interaction.ts
https://github.com/becomposable/studio/issues/498
For the Interaction Execution API, it will have a new, optional parameter "run_data" which allows user to control the level of storage for the data related to a run of an interaction: "standard", "restricted", or "debug". If parameter overrides the value defined in Studio, which provides more flexibility to executions.
* Create an interaction with Run Data configured as STANDARD.
* Build the `composable` command line 
* Run the interaction locally with different levels: undefined, DEBUG, STANDARD, RESTRICTED, NON_EXISTENT; and with different cases. Ensure that the run data are stored correctly.
```sh
pnpm -r build
cd packages/cli
```
See the new option "-r", "--run-data" in the help message of the command line:
```
node lib/index.js run -h …
```
=> feat(498): expose optional param "run_data" for Interaction Execution API

packages/common/src/store/temporalio.ts, pnpm-lock.yaml
When regenerating pnpm-lock the build will fail due to ParentClosePolicy changes in version 1.11.5 of Temporalio/sdk-typescript.
ParentClosePolicy in composableai/common is updated to work with the new changes.
=> Update pnpm-lock and update ParentClosePolicy to work with new temporalio changes

packages/common/src/environment.ts, packages/common/src/interaction.ts, packages/workflow/src/activities/executeInteraction.ts
* https://github.com/becomposable/studio/issues/616
=> Extend types from ModelOptions to support new LLM parameters.

packages/workflow/src/conversion/mutool.test.ts
Extends the timeout for mutool tests from the default of 5 seconds to 10 seconds.
CI Tests are failing intermittently due to timeout:
https://github.com/becomposable/composableai/actions/runs/12032668948/job/33545089180
And when successful tests for mutool.test.ts add up to over 5 seconds, so it could be quite marginal.
https://github.com/becomposable/composableai/actions/runs/11800116133/job/32870326438
=> fix:extends timeout for mutool test

packages/converters/package.json, packages/converters/src/image.test.ts, packages/converters/src/image.ts, packages/workflow/src/conversion/image.test.ts, pnpm-lock.yaml
This function had been replaced by `pdfToImages`. Let's remove it.
=> chore(761): remove pdfToImage

packages/common/src/interaction.ts
* https://github.com/becomposable/studio/issues/86
Allows ModelOptions properties in InteractionUpdatePayload inherited from Interaction to be null.
For use as a special value indicating that the property should be cleared.
Related studio PR:
* https://github.com/becomposable/studio/pull/744
=> Fix(86): Allow ModelOptions in InteractionUpdatePayload to be null

pnpm-lock.yaml
* https://github.com/vertesia/composableai/commit/e8e6c10e804eceb58edad197711eb27990d0bce0
Above commit broke the build on github.
Removing pdf2md from matching location in pnpm-lock to fix build.
No functional change. If it builds, it is good to go.
=> fix build: Remove pdf2md from packages/workflow pnpm-lock

packages/client/package.json, packages/client/src/client.test.ts, packages/client/src/client.ts
This PR introduces a new parameter "site" for the Vertesia API Client. You can use this to specify which site you want to talk to, which is either for the production environment, preview, or staging. If the site is not specified, it defaults to the production site `api.vertesia.io`.
So in most cases, a developer will use it like this without any parameters:
```ts
const client = new VertesiaClient();
```
Or if he/she wants to switch to the preview or staging environment:
```ts
const client = new VertesiaClient({
site: 'api-preview.vertesia.io',
});
```
This PR also makes the previous URL parameters optional. If defined, they will take precedence over the "site" parameter. This is mainly useful for local development or custom solutions.
```ts
const client = new VertesiaClient({
serverUrl: …
```
=> feat: support parameter "site" in the Vertesia Client

packages/workflow/src/activities/generateOrAssignContentType.ts
Currently existing content types are logging as:
```
Execute SelectDocumentType interaction on content with 
existing types: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]
```
Fixed using .map
=> fix: log existing content types using .map

packages/client/src/store/CommandsApi.ts, packages/client/src/store/EmbeddingsApi.ts, packages/client/src/store/client.ts
Recently, we introduced the Unified API in our backend. We cannot have the same resource path in both Studio and Zeno anymore. Otherwise, it creates some conflicts for the API routes. This PR adds the Embeddings API to the top level to mitigate the problem. The old API is marked as deprecated but it is still present. It will be removed once we have the new endpoints in our production.
=> feat: move Embeddings API to top-level

packages/workflow/src/activities/generateDocumentProperties.ts
* https://github.com/vertesia/studio/issues/1418
Previously the text field was being overwritten causing some issues, then a fix was added which stopped writing to it at all.
This fix writes to the field with fallbacks if there is no text already, solving the overwriting issue while giving some text.
This mostly applies to image content and natural language search of embeddings, so the issue can be more completely addressed by using image embeddings.
* https://github.com/vertesia/studio/issues/1624
=> fix: Populate text field in generateDocumentProperties

packages/workflow/package.json, packages/workflow/src/dsl/dsl-workflow.ts, packages/workflow/src/dsl/workflow-exec-child.test.ts, packages/workflow/src/dsl/workflow.test.ts, pnpm-lock.yaml
This PR sets the search attributes "AccountId" and "ProjectId" to child workflows, allowing them to be searchable using these attributes.
https://community.temporal.io/t/how-to-define-custom-search-attribute-in-a-typescript-test-environment/10589
=> feat: set search attributes for child workflows

packages/common/src/query.ts
This is necessary to make matching prompts with interactions optional.
* https://github.com/vertesia/studio/pull/1768
=> feat: adds matchInteractions property to prompt search query

packages/common/src/query.ts
Used to pass multiple interaction to the endpoint at once.
We are using this to list multiple versions of an interaction at once.
* https://github.com/vertesia/studio/pull/1819
=> feat: allow interaction to be an array in run listing query

package.json, pnpm-lock.yaml
This PR uses another way to manage the vite version by moving the version declaration to the devDependencies. This is inspired by [vitest](https://github.com/vitest-dev/vitest/blob/main/package.json). It facilitates the security updates and dependency management. This PR also updates Vite to the latest version.
=> chore(deps): unify and update vite

packages/workflow/src/dsl/dsl-workflow.ts, packages/workflow/src/dsl/workflow-exec-child.test.ts, packages/workflow/src/dsl/workflow.test.ts
This PR propagates the value of `InitiatedBy` to child workflows in memo and search attributes so that we can display the data correctly in the UI and for search, too. Note that the field in `memo` is a fallback and will be removed once the search attributes are fully deployed to production.
=> fix: propagate the value of InitiatedBy

packages/common/src/store/workflow.ts
- Temporal events for activity include references to past events. Without these references, it is impossible to know which activity the event is related to.
- Make values that are not always present optional (so we don't need to set these to empty string)
=> feat: add missing properties in workflow run event

packages/workflow/src/activities/advanced/createDocumentTypeFromInteractionRun.ts, packages/workflow/src/activities/advanced/createOrUpdateDocumentFromInteractionRun.ts, packages/workflow/src/activities/advanced/updateDocumentFromInteractionRun.ts, packages/workflow/src/activities/createDocumentFromOther.ts, packages/workflow/src/activities/executeInteraction.ts, packages/workflow/src/activities/extractDocumentText.ts, packages/workflow/src/activities/generateEmbeddings.ts, packages/workflow/src/activities/media/processPdfWithTextract.ts, packages/workflow/src/activities/media/transcribeMediaWithGladia.ts, packages/workflow/src/activities/notifyWebhook.ts, packages/workflow/src/activities/renditions/generateImageRendition.ts, packages/workflow/src/activities/renditions/generateVideoRendition.ts, packages/workflow/src/dsl/dsl-workflow.ts, packages/workflow/src/dsl/setup/ActivityContext.ts, packages/workflow/src/errors.ts, packages/workflow/src/utils/blobs.ts, packages/workflow/src/utils/client.ts
Currently, the errors thrown by the workflow can be retried, but they are not retryable. This PR provides new error types that wrap the non-retryable error `ApplicationFailure` from Temporal SDK to mark the activity or workflow execution as failed. Therefore, callers won't need to specify a custom retry policy anymore.
=> feat: declare non-retryable error types

packages/ui/src/features/agent/chat/ModernAgentOutput/Header.tsx
There was a "start a new agent" in the action of the current agent; the following issues were raised
- It's hard to find for first-time user
- should not mix with the current agent action
=> feat: remove start a new agent from current agent action

packages/workflow/src/errors.ts
These types are replaced by the non-retryable version, so they are no longer used. They can be safely removed.
=> chore: remove deprecated workflow types

packages/ui/src/features/facets/VFacetsNav.tsx
On the Content Objects Page, the `by Name or ID` was not working 
The problem was found in the API call, the column name was not aligned
This PR fixed the problem and tested as shown in screenshot
=> Fix: name filter was not working on content object

packages/ui/src/features/facets/VFacetsNav.tsx
=> Fix: name filter was not working on content object (#311)

packages/ui/src/features/store/objects/components/DocumentIcon.tsx, packages/ui/src/features/store/objects/components/SelectDocument.tsx, packages/ui/src/features/store/objects/layout/documentLayout.tsx
Inside Interaction > Playground, you can select an object from a content object table, which allows the user to view it as a table or a thumbnail. There were the following issues.
- https://github.com/vertesia/studio/issues/2111 
-  The problem was found because the default click behavior set on the grid view is to navigate to the object page, instead of being set by a caller function like the table view
- The fix in this PR will pass down the `onRowClick` behavior to the Grid Rendering Component 
- https://github.com/vertesia/studio/issues/2106
- The problem was found while the button was getting the last view status from the `localstorage`, the table was initialized as `table` every time
- The fix in this PR will align both by fetching the last view status from the `localstorage`
=> Fix: Content objects grid view

packages/ui/src/core/components/EmptyCollection.tsx, packages/ui/src/features/store/collections/CollectionsTable.tsx, packages/ui/src/features/store/collections/CreateCollection.tsx, packages/ui/src/features/store/types/ContentObjectTypesSearch.tsx
- Update `EmptyCollection` component to use `h-full` instead of `min-h-full`
- Apply flexbox centering to fill the remaining screen height
- Fix layout across training, settings, interactions, prompts, and store types pages
- Ensure a consistent empty state experience across all pages
- Handle empty view on collections list
=> feat: improve empty state layouts with full-height centering

packages/ui/src/features/store/objects/DocumentSearchResults.tsx, packages/ui/src/features/store/objects/components/DocumentIcon.tsx, packages/ui/src/features/store/objects/components/SelectDocument.tsx, packages/ui/src/features/store/objects/components/SelectDocumentModal.tsx, packages/ui/src/features/store/objects/layout/renderers.tsx
* https://github.com/vertesia/studio/issues/2251
- Add refresh button for **Select Object** modal in the Playground and **Link Object** model in Agent Runner, next to the button for switching between table and thumbnail views.
- Add placeholder text for missing thumbnails: `Preparing preview`.
- Improve navigation from Object table and thumbnail views to open the object (vs. expand the side panel) using a button icon.
=> Fix: optimize thumbnail view handler

packages/ui/src/features/utils/rendition.ts
Sometimes, the retrieval of the rendition of an object fails because the rendition generation is in progress or because the source attached to the object is incorrect. In these cases, the backend API returns a 4xx error and the UI should not treat it as an error because this is not incorrect behavior in the frontend.
=> fix: use warn() for rendition failures

packages/ui/src/features/agent/chat/ModernAgentOutput/MessageItem.tsx, packages/ui/src/features/store/objects/components/ContentOverview.tsx
- The previous approach was if the url start with `/store` then we use internal navigator, otherwise it will just use `a` tag
- But the object that agent created, the link is `https://cloud.vertesia.io/store/objects/123` which will not apply to the previous logic
- This PR changes the logic to check if the url contains `/store/objects/` 
- And instead of using `Link`, ues `NavLink` to maintain the router better
=> Fix: link in object not found if created by agent 

packages/ui/src/core/components/toast/NotificationPanel.tsx
Switches the toast message to use the global css attributes e.g. bg-muted
=> fix: use global css attributes for toast

packages/ui/src/router/HistoryNavigator.ts
getElementHrefAsUrl would cause `Failed to construct 'URL': Invalid URL ` errors when the Href was invalid.
=> fix: safer getElementHrefAsUrl

packages/converters/src/image.test.ts, packages/ui/src/features/store/objects/DocumentPreviewPanel.tsx, packages/ui/src/features/store/objects/components/ContentOverview.tsx, packages/workflow/src/activities/generateEmbeddings.ts, packages/workflow/src/activities/generateOrAssignContentType.ts, packages/workflow/src/activities/renditions/generateImageRendition.ts, packages/workflow/src/conversion/image.test.ts
Uses 1596 instead of 1024 as the default max_hw, thumbnails still use 256
=> fix: consistent default rendition max_hw of 1596

packages/common/src/store/workflow.ts, packages/ui/src/core/components/FormItem.tsx, packages/ui/src/features/agent/chat/ModernAgentConversation.tsx, packages/ui/src/features/agent/chat/ModernAgentOutput/AllMessagesMixed.tsx, packages/ui/src/features/agent/chat/ModernAgentOutput/MessageItem.tsx, packages/ui/src/features/agent/chat/ModernAgentOutput/SlidingMessages.tsx, packages/ui/src/features/agent/chat/ModernAgentOutput/utils.ts
* https://github.com/becomposable/studio/issues/1875
- The workflow is now returning the failed message, but instead of showing `completed`, the more accurate status should be `terminated`
- This PR adds a terminated status, and handles it accordingly
=> handle terminated status for agent

packages/client/src/AccountApi.ts, packages/common/src/transient-tokens.ts, packages/common/src/user.ts, packages/ui/src/shell/login/InviteAcceptModal.tsx
* https://github.com/vertesia/studio/issues/2131
1. Update database Schema
- Create `InvitationDataSchema` which defines all the columns in the documents to increase type security
- Store `ObjectId` for project, account, invitedBy, and only populate the related information when returning the api response
- Schema
```typescript
export const InvitationDataSchema = new mongoose.Schema<UserInviteTokenData>({
email: { type: String, required: true },
role: { type: String, required: true },
account: { type: mongoose.Types.ObjectId, ref: 'Account', required: true },
project: { type: mongoose.Types.ObjectId, ref: 'Project', required: true },
invitedBy: { type: mongoose.Types.ObjectId, ref: 'User', required: true }
}, { _id: false });
```
---
2. Update the invitation accept modal to show the …
=> Feat: Invitation accept parameter

packages/client/src/AppsApi.ts
Settings are stored outside the app manifest, and app installations did not have any update endpoints.
For studio pr [#2519](https://github.com/vertesia/studio/pull/2519)
=> feat: add endpoint to update app installation settings

packages/ui/src/features/store/collections/CreateCollection.tsx
If you hit the "enter" key while typing in the new collection modal, it closes the modal without creating the collection or saving the work. 
For example, if you fill out the modal and hit "enter", it actually closes and clears the modal instead of creating the collection.
Fix: remove default form handling to disable enter key.
Studio PR: https://github.com/vertesia/studio/pull/2573
=> fix: disable 'enter' keyboard key when making a collection

packages/workflow/src/system/recalculateEmbeddingsWorkflow.ts
The recalculate embeddings workflow was going through all embedding types regardless of what was specified in the payload.
This significantly increases the traffic when re-embeddings, especially due to image embeddings triggering many generateRenditions
=> fix: recalculate embeddings respects requested type 

packages/ui/src/features/store/objects/DocumentSearchResults.tsx
Due to react component initialisation there were 2 empty searches on page load.
Adding a guard clause, to block the superfluous one.
=> fix: remove duplicate search on content objects page load

packages/common/src/interaction.ts
The documentation of the API is incorrect. The unit used in the internal system is in milliseconds.
=> fix: time unit for execution

packages/ui/src/core/components/shadcn/filters/filterBar.tsx, packages/ui/src/features/facets/DocumentsFacetsNav.tsx, packages/ui/src/features/facets/utils/VTypeFacet.tsx
- Current filter stores the value in the URL, to keep the filter while navigating, and there is an error if an object type filter is applied.
- The cause is coming from the URL decoding. If there is only one value for types, it would be treated as a string, but the backend is expecting an array
- The fix is to keep the bracket in the URL, so when decoding from the URL, it would still apply the corresponding format
=> fix: url handling for array format

packages/client/src/store/ObjectsApi.ts
The existing ComputeFacetResponse.total is `total?: { count: number }[];`
However this is not actually respected we use `total: number`.
Changing the type to reflect this.
=> fix: facet response total, use total: number

packages/ui/src/core/components/table/index.tsx, packages/ui/src/features/store/objects/components/DocumentIcon.tsx, packages/ui/src/features/store/objects/layout/documentLayout.tsx
Add loading status view for thumbnail, to prevent double spinner view
=> Feat: add loading status view for thumbnail

packages/ui/src/features/store/objects/components/ContentOverview.tsx
- When there is no image, the image button is hidden, but the text button is still clickable
> This fix hides the button and does nothing for the remaining text button
- If the text is long, it overflows the view and scrolls is the entire page
> This fix the limit on the height of the text panel and scrollable within the panel
https://github.com/user-attachments/assets/a277fd9f-79fe-41d2-8ad3-0d0b4b17b12a
=> fix: Content Object text and image switcher behavior

.github/workflows/publish-npm-dev.yaml, package.json
When merging a new commit to the `main` branch, we would like to create a snapshot (dev) version of all the packages to the NPM registry, which may facilitate the development of our users. For example, if someone wants to develop a Vertesia Plugin. Right now, they have to use the release version, which is 0.78.0, released one month ago. With the new mechanism, users can use the latest version.
I ran the script locally and published a new dev version for the memory pack:
=> feat: publish dev packages on main
