vertesia/composableai

packages/cli/src/objects/commands.ts, packages/cli/src/objects/index.ts
- Add content type selection from list when uploading a new content
- Add update content type command
=> feat(218): Update content command

.github/workflows/main.yaml, package.json
... which allows contributors to detect build failures earlier during the development.
=> Setup GitHub Actions for Composable AI

packages/workflow/src/activities/generateOrAssignContentType.ts, packages/workflow/src/activities/index.ts, packages/workflow/src/index.ts
Rename guessOrCreateDocumentType to generateOrAssignContentType for composableai repo.
https://github.com/becomposable/studio/issues/259
=> Rename guessOrCreateDocumentType to generateOrAssignContentType

packages/common/src/interaction.ts
... which is more explicit and easy to understand. This is related to
* https://github.com/becomposable/studio/issues/498
=> feat: replace RestrictionLevel by RunDataStorageLevel

packages/common/src/interaction.ts
Cherry-pick https://github.com/becomposable/composableai/pull/48 to the `preview` branch
=> feat: replace RestrictionLevel by RunDataStorageLevel (#48)

.gitmodules
* https://github.com/becomposable/studio/issues/653
=> chore: change repo link of llumiverse

packages/common/src/interaction.ts
Adds finish_reason and chunks to ExecutionRun type
- https://github.com/becomposable/studio/issues/617
=> Adds finish_reason and chunks to ExecutionRun type

pnpm-lock.yaml
Updating to pnpm-lock generated from pnpm i process.
=> Fix: Resolve build error by updating pnpm-lock

packages/cli/src/datagen/index.ts, packages/common/src/environment.ts, packages/common/src/interaction.ts, packages/workflow/src/activities/executeInteraction.ts, packages/workflow/src/iterative-generation/utils.ts
Tracking issue:
* https://github.com/vertesia/studio/issues/1056
Related PR:
* https://github.com/vertesia/studio/pull/1055
=> Reformat run and interaction DB formats to nest ModelOptions

packages/common/src/query.ts
* https://github.com/vertesia/studio/issues/1078
=> allow run to filter with finish reason and the user who created

packages/client/src/store/CollectionsApi.ts, packages/client/src/store/TypesApi.ts, packages/client/src/store/client.ts, packages/common/.vscode/settings.json, packages/common/src/store/collections.ts, packages/common/src/store/index.ts, packages/common/src/store/store.ts
https://github.com/vertesia/composableai/issues/104
=> Added store collection types

packages/common/src/store/collections.ts
We were missing some changes in the previous version
=> Release 21 Feb 2025 (V2)

package.json
This is related to
* https://github.com/vertesia/llumiverse/pull/81
=> Update pnpm version to 9.15.2

packages/common/src/project.ts
add auto config parameter to project interface, so that it can be passed to backend
=> add auto config option

.github/workflows/main.yaml
This is a leftover task from the previous PR https://github.com/vertesia/composableai/pull/133
=> feat: add client tests in the CI

packages/common/src/user.ts
* https://github.com/vertesia/studio/issues/1534
=> feat: remove project and run from onboarding

.github/workflows/main.yaml, packages/workflow/package.json, packages/workflow/src/activities/generateImageRendition.ts, packages/workflow/src/conversion/image.test.ts, packages/workflow/src/conversion/image.ts, packages/workflow/src/conversion/pandoc.test.ts, packages/workflow/src/utils/blobs.ts, pnpm-lock.yaml
This PR backports the following changes from preview to staging:
* https://github.com/vertesia/composableai/pull/153
* https://github.com/vertesia/composableai/pull/154
=> Use ImageMagick for renditions instead of Sharp (backport)

packages/workflow/src/activities/generateImageRendition.ts, packages/workflow/src/conversion/image.ts
See https://github.com/vertesia/composableai/pull/169
=> fix: Enhance image rendition process with improved parameter handling (backport)

packages/workflow/src/activities/media/transcribeMediaWithGladia.ts
https://github.com/vertesia/studio/issues/1762
=> fix: use access_token for the Gladia callback

packages/common/src/store/workflow.ts, packages/workflow/src/dsl/dsl-workflow.ts, packages/workflow/src/dsl/workflow-exec-child.test.ts, packages/workflow/src/dsl/workflow.test.ts
... which allows searching the workflow executions based on document ID(s)
=> feat: set documentId as search attributes for child workflows

packages/client/package.json, packages/client/src/execute.ts, packages/client/src/store/WorkflowsApi.ts, pnpm-lock.yaml
Requires some code changes with the new import style in eventsource 3 as opposed to eventsource 1.
=> chore(deps): upgrade to eventsource 3

packages/workflow/src/activities/extractDocumentText.ts, packages/workflow/src/conversion/markitdown.ts, packages/workflow/src/conversion/pandoc.test.ts, packages/workflow/src/conversion/pandoc.ts
- Add support for PPTX to Markdown conversion using markitdown
- Rename pandoc conversion function for clarity
- Improve code formatting and organization
- Test PPTX file conversion to markdown
- Verify existing formats still work properly
=> Feat: Implement PPTX to Markdown conversion

VERTESIA.md
This PR introduces a new file `VERTESIA.md` to describe the development guidelines across sessions, like style guidelines and common commands in our workflow.
=> feat: add VERTESIA.md

packages/cli/src/workflows/index.ts
This fix makes it possible to actually provide a queue name
=> fix: get queue value

packages/common/src/store/workflow.ts
Add workflow type in to payload interface to add type into the temporal query
=> Feat: add workflow type in to payload interface

packages/client/src/store/FilesApi.ts, packages/common/src/store/store.ts, packages/workflow/src/activities/renditions/generateVideoRendition.ts, packages/workflow/src/utils/renditions.ts
- Enhance video rendition generation with multiple thumbnail support
- Add video metadata extraction using ffmpeg
- Refactor and optimize rendition utility functions
- Improve error handling and logging in rendition activities
- Refactored store.ts for improved code organization
- Enhanced video rendition generation with better error handling
- Added support for generating multiple thumbnails at different timestamps
- Implemented video metadata extraction capabilities
=> feat: enhance video rendition generation with multiple thumbnails and metadata extraction

packages/ui/src/core/components/shadcn/dialog.tsx, packages/ui/src/core/components/styles.ts, packages/ui/src/core/components/table/index.tsx, packages/ui/src/layout/FullHeightLayout.tsx
- Adjust the spacing in different components 
- Adjust Styling for the input box
=> Fix: collections

packages/ui/src/core/components/shadcn/button.tsx
create copy button component  for better styling consistency
=> Feat: create copy button component 

packages/ui/externals.js, packages/ui/package.json, packages/ui/src/core/components/shadcn/calendar.tsx, packages/ui/src/core/components/shadcn/filters/comboBox.tsx, packages/ui/src/core/components/shadcn/filters/dateFilter.tsx, pnpm-lock.yaml
use `react-date-picker": "^11.0.0"` for date selector
=> Fix: date selector in filterBar

packages/common/src/payload.ts
Update ComputeObjectFacetPayload to handle vectorSearch and match properties
=> fix: Update ComputeObjectFacetPayload interface

packages/client/src/store/WorkflowsApi.ts, packages/common/src/interaction.ts, packages/common/src/store/workflow.ts, packages/ui/externals.js, packages/ui/package.json, packages/ui/src/features/agent/PayloadBuilder.tsx, pnpm-lock.yaml
- Retrieve interaction from the workflow on agent
=> Feat: agent interaction display

packages/ui/package.json, packages/ui/src/features/agent/PayloadBuilder.tsx, pnpm-lock.yaml
Makes adjustments in the payload builder for agent runner.
=> fix: interaction model, clear on environment change or use default model

pnpm-lock.yaml
=> chore(sync): sync llumiverse to main

packages/common/src/store/workflow.ts
Feat: add interaction field to store the interaction name (#325)
=> Sync code from "Preview" (928528db0369ec3a07a46e5262defe88d58905bd)

packages/ui/src/features/agent/chat/ModernAgentOutput/MessageItem.tsx, packages/ui/src/features/store/objects/components/ContentOverview.tsx, packages/ui/src/features/store/objects/components/PropertiesEditorModal.tsx, packages/ui/src/features/store/types/ContentObjectTypesTable.tsx, packages/ui/src/features/store/types/CreateOrUpdateTypeModal.tsx, packages/ui/src/widgets/codemirror/CodeMirrorEditor.tsx
Fix: Update content object after save (#341)
=> Sync code from "preview" (f7d952c590541eaabbebab82e780753b75b72fe9)

packages/ui/src/features/store/objects/components/ContentOverview.tsx
Get some changes from preview into main
=> chore(sync): preview to main

packages/ui/src/core/components/Badge.tsx, packages/ui/src/core/components/InputList.tsx, packages/ui/src/core/components/shadcn/filters/filterBar.tsx
Update component style to handle cases where input is too long
=> fix: Update component style

packages/ui/src/core/components/shadcn/command.tsx, packages/ui/src/core/components/shadcn/filters/DynamicLabel.tsx, packages/ui/src/core/components/shadcn/filters/filterBar.tsx, packages/ui/src/core/components/shadcn/filters/selectFilter.tsx, packages/ui/src/features/facets/VUserFacet.tsx, packages/ui/src/features/store/objects/components/VectorSearchWidget.tsx, packages/ui/src/features/user/UserInfo.tsx
https://github.com/vertesia/studio/issues/2334
=> feat: Update user filters style

packages/ui/src/core/components/shadcn/filters/comboBox/DateCombobox.tsx, packages/ui/src/core/components/shadcn/filters/comboBox/TextCombobox.tsx, packages/ui/src/core/components/shadcn/filters/filter/SelectFilter.tsx, packages/ui/src/core/components/shadcn/filters/filter/TextFilter.tsx, packages/ui/src/core/components/shadcn/filters/filter/dateFilter.tsx, packages/ui/src/core/components/shadcn/filters/filterBar.tsx, packages/ui/src/features/facets/DocumentsFacetsNav.tsx, packages/ui/src/features/facets/RunsFacetsNav.tsx, packages/ui/src/features/facets/VFacetsNav.tsx, packages/ui/src/features/facets/WorkflowExecutionsFacetsNav.tsx, packages/ui/src/features/facets/index.ts, packages/ui/src/features/store/objects/DocumentSearchResults.tsx, packages/ui/src/features/store/objects/components/SelectDocument.tsx
- group name
- options
- action button: apply and cancel
- create filter provider to arrange the layout
=> Feat: update filter styling

packages/ui/src/core/components/FormItem.tsx
Example:
Usage:
```typescript
<FormItem label="Disabled Field" disabled>
<Input type="text" placeholder="Disabled field" disabled/>
</FormItem>
```
=> feat: add disable status for formItem

packages/common/src/access-control.ts, packages/common/src/apikey.ts, packages/common/src/apps.ts, packages/common/src/project.ts, packages/ui/src/shell/apps/CheckAppAccess.tsx
See https://github.com/vertesia/studio/issues/2453
=> changed apps_roles to apps

packages/ui/src/features/facets/RunsFacetsNav.tsx
=> Fix runs list: restore tags filter and infinite scrolling

packages/ui/externals.js, packages/ui/package.json, packages/ui/src/core/components/Overlay.tsx, packages/ui/src/core/components/index.ts, pnpm-lock.yaml
[#2552](https://github.com/vertesia/studio/issues/2552)
Add Overlay component to available UI components
=> feat-2552: Add Overlay Component

packages/ui/src/core/components/SidePanel.tsx, packages/ui/src/core/components/shadcn/tabs.tsx
- Tab
- Before we pass the `currentTab` function to the tab components every time to retrieve the value from the URL
- This Pr moves the function to the component level, so that we don't need to pass the same function every time 
- SidePanel
- update with `motion.div` instead of Dialog
- Add backdrop option
=> Feat: update tab and sidepanel behavior

packages/ui/src/features/agent/PayloadBuilder.tsx
Enhance the model selection process by prioritizing the interaction model over the environment's default model when applicable.
=> Fix: agent default model selection logic

packages/common/src/store/store.ts, packages/ui/src/features/store/objects/DocumentSearchResults.tsx, packages/ui/src/features/store/objects/components/DocumentIcon.tsx, packages/ui/src/features/store/objects/search/DocumentSearchContext.ts
- Show spinner when the page first loads
- round up the search score to 4 decimal places
- show search score in grid view
=> Feat: objects view

packages/client/src/store/ObjectsApi.ts
=> fix: avoid empty headers in object create / update

packages/common/src/payload.ts
New default behaviour for : https://github.com/vertesia/studio/pull/2743
reflected in comment
=> fix: update comment for limit_facets

packages/ui/externals.js, packages/ui/package.json, packages/ui/src/core/components/SidePanel.tsx, packages/ui/src/core/components/shadcn/index.ts, packages/ui/src/core/components/shadcn/resizeable.tsx, packages/ui/src/features/store/collections/SelectCollection.tsx, pnpm-lock.yaml
Create a resizable div based on the `shadcn` library
=> Feat: resizeable

packages/ui/src/features/store/objects/DocumentSearchResults.tsx
see [2567](https://github.com/vertesia/studio/issues/2567)
=> use sticky search bar

packages/ui/src/features/store/objects/components/ContentOverview.tsx
- Add Resiable panel
- Add Panel switcher for left and right
- Properties and JSON
- Text and Image (if exists)
- Remove Text view border
=> Feat: object page

packages/common/src/interaction.ts, packages/tools-sdk/src/ToolCollection.ts
Changes:
- Fixed ToolCollection.ts: Added explicit Promise<Response> return type annotation to resolve
TypeScript inference error
=> Fix: tools build
